### PR TITLE
build: move `@polkadot/x` out of `dependencies`

### PR DESCRIPTION
**Pull request by tien**
since it's part of `peerDependencies` this will allow dependent package to target their desired `@polkadot/api` version

### CODE REVIEW

**Comment by qwer951123** [comment]
👍  LGTM, thank you

**Comment by qwer951123** [comment]
but there are some lint errors that need to be fixed.

**Comment by tien** [comment]
@qwer951123 looks like a Yarn problem where multiple versions of `@polkadot/*` was resolved. Have fixed this by running `yarn dedupe '@polkadot/*'`

**Comment by qwer951123** [comment]
will merge these changes temporarily, and make adjustments in some places later if necessary.

**Pull request merged**
